name = "hellomegbot"
main = "src/worker.ts"
compatibility_date = "2026-02-07"

[vars]
HELLOMEG_HIGH_TEMPERATURE_ENABLED = "true"
HELLOMEG_HIGH_TEMPERATURE_THRESHOLD_CELSIUS = "30"

[observability.logs]
enabled = true

[assets]
directory = "./src/assets"
binding = "ASSETS"
